### ISSUE TITLE
Linter runs on all files, not just meson build files

### ISSUE THREAD

**Issue by akberg** [mesonbuild/vscode-meson#146]
OS: Fedora 38
vscode: 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06)

When enabling linting with muon, the linter starts targeting all files in the project, reporting errors on json files and cpp sources. Is there a way to specify which files muon is supposed to check? (And that should maybe default to only list meson.build files)

**Comment by Totto16** [comment]
The same thing happens to me, and the interesting thing is, that it only happens if the open folder contains a meson.build. (or similar)
It works fine, if my project doesn't have a meson file, so that is totally weird, since I at least think, the linter is only triggered on certain files? (meson.build, meson.options, meson-options.txt) but it seems, if the linter sees one such file, from that time on, he just lints every file :sweat:

**Comment by tristan957** [comment]
This was fixed inhttps://github.com/mesonbuild/vscode-meson/commit/d9f0d5a5aaa3fabece2e32ea64a6da906162dec9. Stay tuned for a release!
