### ISSUE TITLE
Meson isn't picked up from the `PATH`

### ISSUE THREAD

**Issue by paveloom** [mesonbuild/vscode-meson#181]
I'm using [Nix](https://nixos.org), [`direnv`](https://github.com/direnv/direnv), and [`nix-direnv`](https://github.com/nix-community/nix-direnv) to setup a development environment. I'm using the [`direnv` VSCode extension](https://github.com/direnv/direnv-vscode) to load that environment in VSCode. This extension can't find Meson that is provided by the environment:

```
The terminal process failed to launch: Path to shell executable "meson" does not exist.
```

 I think that's because you're using [`ProcessExecution`](https://code.visualstudio.com/api/references/vscode-api#ProcessExecution) instead of [`ShellExecution`](https://code.visualstudio.com/api/references/vscode-api#ShellExecution). I poked around and found that you made a switch to `ProcessExecution` in https://github.com/mesonbuild/vscode-meson/pull/47 to avoid shell escaping issues. Are those issues still relevant? And if so, won't the second constructor for `ShellExecution` bypass them?

**Comment by tristan957** [comment]
@lukester1975 can you check this out?

**Comment by lukester1975** [comment]
Erm, dunno. Looks like it's all changed since those mods by me! 

I did mention `ShellQuoting` in that issue, but sadly I don't recall if that means I tried the second ctor and still had issues or what. The vscode type defs were old at the time but that second ctor was still there AFAICT. Sorry, not much help.

That said, FWIW, I just  `s/ProcessExecution/ShellExecution/` on main and it still worked for the couple of things I threw at it. But day-to-day I'm still on my old multiple build dir branch, so that change won't get much more testing from me!

Maybe it's best for @a paveloom to try running with those mods and see how it goes; seems a bit silly me making a PR for it?

**Comment by tristan957** [comment]
If you don't want to PR it, I can. I'll take your experience as an endorsement for merging. When do you think you'll get your multiple build directory branch up for PR? I'd be really likely to merge it given you run it all the time.

**Comment by lukester1975** [comment]
OK #186. As long as I don't get blamed...

R.e. multiple build dirs - lord knows. So much has changed and cursorily it looks like more stuff assumes a single build dir. It would be a complete rewrite I imagine, so probably unlikely until either a) my old branch no longer works with current vscode or b) there's something so good in the latest meson plugin that I want both bits of functionality...

Maybe I could rebase some of the trivial stuff one day and at least make a start that way.

Cheers

**Comment by tristan957** [comment]
No problem. Thanks for looking.
