### ISSUE TITLE
Cannot build library targets

### ISSUE THREAD

**Issue by IanAshleyEckoh** [mesonbuild/vscode-meson#24]
A error is reported that the target cannot be found when building library targets. It looks like the issue is that the name of file built does not match the target name due to the suffix.

I have attached a sample project that demonstrates the issue. The all and SimpleMathsMain targets can be built using the plus whereas the SimpleMaths target cannot.

Thanks for an excellent additional to VS Code.

[SimpleMaths.zip](https://github.com/asabil/vscode-meson/files/5428485/SimpleMaths.zip)

**Comment by btgoodwin** [comment]
I see this issue as well, where the `build.ninja` file is produced with a target like `subdir/lib<some_name>.so` where `subdir/meson.build` has something like:

```
some_lib = shared_library('some_name', sources, ...)
```

Looking at this further, it is using `meson introspect` which gives target names that `meson` recognizes but ninja won't necessarily recognize.  A fix would be to drop directly calling ninja in [tasks.ts](https://github.com/asabil/vscode-meson/blob/master/src/tasks.ts) and instead do something like this for the compile task, for example:

```
meson compile -C builddir <some_name>
``` 

Unfortunately meson's CLI API isn't as straight-forward as `meson <verb> -C <build directory> <args>` for all its verbs.  Some the build directory is the last arg and `-C` isn't a thing, so it might require a bit more poking around to get this working more cleanly.

An alternative might be to modify the introspection check to see the `type` is `shared library` and then parse `filename` to infer what the ninja-friendly target name will be.

I realize this issue is months old but does anyone have an opinion of which would be more appropriate?

**Comment by vnen** [comment]
> Unfortunately meson's CLI API isn't as straight-forward as `meson <verb> -C <build directory> <args>` for all its verbs.

Why is that a problem? To fix this issue it would suffice to run `meson compile <target>` instead of `ninja <target>`. What difference does it make that other verbs have different interface?

I also argue that using `meson compile` is better than `ninja` in any case, especially if this extension wants to support other build backends.

**Comment by btgoodwin** [comment]
As I said in the sentence immediately following the one you quoted, my point was that refactoring wouldn't be a simple find-replace for ninja -> `meson -C` for example since some of the `meson` verbs don't have that CLI option (`-C`).  Some expect the build directory to be the last argument, some expect you to use `-C` so refactoring would mean sorting out those differences and applying them as one replaced the `ninja` calls with the equivalent `meson` verb/options list.

I otherwise agree with you, I feel like excluding `ninja` calls and instead letting `meson` verbs define what underlying tool to call is the way to go.  I haven't had time the last few nights to mess with this though.

**Comment by Ongy** [comment]
Is this still an open issue? Looking at the code, everything is using meson by now and I can build libraries (though I only have static in my test project) just fine with the current code.

**Comment by btgoodwin** [comment]
Yes it seems to be working fine now.  It was probably 318c1df82f7eedfc6456719e711276d95b1d7242 that handled this around 3 months ago.  I apologize for never getting around to submitting a PR for this.
