### ISSUE TITLE
Improve readme: What are the supported provider?

### ISSUE THREAD

**Issue by g-berthiaume** [mesonbuild/vscode-meson#89]
In the readme:
> Linting*
Formatting*
> \* - requires a supported provider be installed

What are the supported providers? 
Is there some documentation about it somewhere?

**Comment by dcbaker** [comment]
@annacrombie :)

**Comment by annacrombie** [comment]
The only current provider is [muon](https://muon.build/), which provides both linting and formatting.  Since I'm the author of muon (and the author of the linting and formatting PR) I would feel a little bit self-serving putting a link to muon in the readme.

I was thinking maybe having a link to a wiki page that lists providers would be the most neutral way to do it.  In reality though, I'm not aware of any progress on any alternative providers, so it might be better to just say `* requires muon` on the readme until more options are available.

**Comment by dcbaker** [comment]
It’s on my list of things to do with Meson++, but I have no idea when I’ll get there, especially for formatting

**Comment by annacrombie** [comment]
I think @tristan957 suggested the same thing, that this extension should auto-download muon.  I would personally avoid an editor plugin that downloads binaries from the internet, but I don't use vscode so maybe this is what vscode users expect.

muon compiles fine on mac but not on windows, although there is someone who has started work on porting muon to windows in the past few weeks.  Since the formatting and analyze functions don't require many os apis (just reading a file), I think getting them to work on windows would be relatively easy.

**Comment by tristan957** [comment]
To put things in perspective, I have the following extensions which download binaries upon updates: `clangd`, `C/C++`, `C#`, `Intellicode`, `Live Share`, etc.

It is definitely not irregular for extensions to download a binary over the wire. Hardest thing to do would be checking for updates on a hosted static `muon` binary.
